
import turtle
turtle.title("I am funny-funny Bear")

turtle.shape('turtle')
# turtle.shapesize(2,2,2)
# turtle.color("green", "green")
turtle.pensize(5)
turtle.speed(1)
turtle.color('black')
turtle.dot(45)

turtle.penup()
turtle.rt(90)
turtle.bk(120)
turtle.rt(90)
turtle.pendown()
turtle.circle(100)

turtle.penup()
turtle.fd(60)
turtle.rt(90)
turtle.pendown()
turtle.circle(50)

turtle.penup()
turtle.lt(90)
turtle.bk(120)
turtle.lt(90)
turtle.pendown()
turtle.circle(50)

turtle.penup()
turtle.lt(90)
turtle.bk(100)
turtle.lt(90)
turtle.bk(60)
turtle.pendown()
turtle.dot(30)

turtle.penup()
turtle.lt(90)
turtle.bk(75)
turtle.pendown()
turtle.dot(30)

turtle.penup()
turtle.rt(90)
turtle.bk(250)
turtle.pendown()
turtle.pensize(1)
turtle.rt(90)
turtle.bk(300)
turtle.rt(90)
turtle.bk(500)
turtle.rt(90)
turtle.bk(500)
turtle.rt(90)
turtle.bk(500)
turtle.rt(90)
turtle.bk(300)